<template>
  <div>
    <Scroll class="content" :probeType="2">
      <ul>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
        <li>dsw</li>
      </ul>
    </Scroll>
  </div>
</template>

<script>
  import Scroll from '../../components/common/scroll/Scroll.vue'
  export default {
    name: "Profile",
    components: {
      Scroll
    }
  }
</script>

<style scoped>
.content {
  height: 300px;
  background-color:red;
  overflow:hidden;
}

</style>
